name: Build & Qodana
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 25

      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew buildAndCollect collectArtifacts

      - name: Get Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: artifacts/

  qodana:
    runs-on: ubuntu-latest
    needs: build  # run Qodana after the build succeeds
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 25

      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v4

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'